# Libor configuration file
prj_name: 'Aclens'
trj: "/media/topo/Data/Data/ALS/Vallet/01_Trj/01_InitialTrajectories/NavGrade/SBET_MILF18_200HZ.out"
p2p_folder: "/media/topo/Data/Data/ALS/Vallet/02_P2P/libor_correctBor/"

t_span: [396500.0, 398000.0]

mount:
  leverArm: [[-0.042], [0.183], [-0.021]] #m
  R_s2b: [[0, -1, 0], [0, 0, -1], [1, 0, 0]]
  initBor: [[0.0] , [0.0], [0.0]] #degrees rpy

tp_latlon: [46.5, 6.5] #decimal degrees

n: 1500 #num cor used in adj.

refBor: [[-0.2123], [0.0996], [0.1914]] #degrees

sigmas: # meters and degrees
  xy: 0.02 
  z:  0.03
  rp: 0.02
  y:  0.03
  p2p: 0.05

logFolder: '/media/topo/Data/Data/ALS/libor/'