# Libor configuration file
prj_name: 'HAR_4'
trj: "/media/topo/Data/Data/ALS/HelimapArpette/01_TRJ/04_IE/SBET.OUT"

p2p_folder: "/media/topo/Data/Data/ALS/libor/in/p2p/arpette/full_wrongbor"

t_span: [289000.0, 294150.0] #time in trj and p2p reference 

mount:
  leverArm: [[0.0], [0.0], [0.15]] #m
  R_s2b: [[0, 1, 0], [0, 0, 1], [1, 0, 0]]
  initBor: [[5.0], [5.0], [5.0]] #degrees rpy

tp_latlon: [46.0, 7.0] #decimal degrees

sampling:
  strategy: 'max'
  value: 5000

refBor: [[0.206], [0.025], [0.352]] # orig. calib.

sigmas:  # meters and degrees
  xy: 0.03
  z:  0.03
  rp: 0.003
  y:  0.005
  p2p: 0.25

riprocess:
  rpy: [0.135,0.016,0.253]
  std: [0.0038,0.0006,0.0068]
  plane_num: 961
  p_sig_prio: 0.29
  p_sig_post: 0.24

dn:
  rpy: [0.206,0.023,0.351]
  std: [0.0001,0.0001,0.0006]

output:
  folder: '/media/topo/Data/Data/ALS/libor/out/wrongbor/'
  fig_svg: true

info: "Arpette - 4 flight lines wrong bor (5° per axis)"