# Libor configuration file
prj_name: 'HAR_4_bias'
trj: "/media/topo/Data/Data/ALS/libor/in/trj/biased/r-02_p-005_y-001_SBET.OUT"

p2p_folder: "/media/topo/Data/Data/ALS/libor/in/p2p/arpette/full_biased_trj/"

t_span: [289000.0, 294150.0] #time in trj and p2p reference 

mount:
  leverArm: [[0.0], [0.0], [0.15]] #m
  R_s2b: [[0, 1, 0], [0, 0, 1], [1, 0, 0]]
  initBor: [[0.0], [0.0], [0.0]] #degrees rpy

tp_latlon: [46.0, 7.0] #decimal degrees

sampling:
  strategy: 'max'
  value: 5000

refBor: [[0.408], [0.075], [0.363]] # orig. calib.

sigmas:  # meters and degrees
  xy: 0.03
  z:  0.03
  rp: 0.003
  y:  0.005
  p2p: 0.1

output:
  folder: '/media/topo/Data/Data/ALS/libor/out/bias/'
  fig_svg: true

info: "Arpette - 4 flight lines with biased trajectory.\n Bias values r,p,y (°): [-0.2, -0.05, -0.01]"