# Libor configuration file
prj_name: 'HAR_2'
trj: "/media/topo/Data/Data/ALS/HelimapArpette/01_TRJ/04_IE/SBET.OUT"

p2p_folder: "/media/topo/Data/Data/ALS/libor/in/p2p/arpette/2fl_nobor/"

t_span: [289000.0, 294150.0] #time in trj and p2p reference 

mount:
  leverArm: [[0.0], [0.0], [0.15]] #m
  R_s2b: [[0, 1, 0], [0, 0, 1], [1, 0, 0]]
  initBor: [[0.0] , [0.0], [0.0]] #degrees rpy

tp_latlon: [46.0, 7.0] #decimal degrees

n: 5000 #num cor used in adj.

refBor: [[0.206], [0.025], [0.352]] # orig. calib.

sigmas:  # meters and degrees
  xy: 0.03
  z:  0.03
  rp: 0.0025
  y:  0.005
  p2p: 0.1


baseline:
  rpy: [0.146,0.013,0.254]
  std: [0.006,0.005,0.025]

output:
  folder: '/media/topo/Data/Data/ALS/libor/out/'
  fig_svg: true

info: "Arpette - 2 flight lines - 090201 & 090603"