# Libor configuration file
prj_name: 'HAR_2'
trj: "/media/topo/Data/Data/ALS/HelimapArpette/01_TRJ/04_IE/SBET.OUT"

p2p_folder: "/media/topo/Data/Data/ALS/libor/in/p2p/arpette/2fl_nobor/"

t_span: [289000.0, 294150.0] #time in trj and p2p reference 

mount:
  leverArm: [[0.0], [0.0], [0.15]] #m
  R_s2b: [[0, 1, 0], [0, 0, 1], [1, 0, 0]]
  initBor: [[0.0] , [0.0], [0.0]] #degrees rpy

tp_latlon: [46.0, 7.0] #decimal degrees

sampling:
  strategy: 'max'
  value: 4000

refBor: [[0.206], [0.025], [0.352]] # orig. calib.

sigmas:  # meters and degrees
  xy: 0.03
  z:  0.03
  rp: 0.0025
  y:  0.005
  p2p: 0.1

riprocess:
  rpy: [0.152,0.007,0.212]
  std: [0.006,0.005,0.027]
  plane_num: 533
  p_sig_prio: 0.28
  p_sig_post: 0.24

dn:
  rpy: [0.211,0.023,0.325]
  std: [0.002,0.0002,0.0005]

output:
  folder: '/media/topo/Data/Data/ALS/libor/out/nominal/'
  fig_svg: true

info: "Arpette - 2 flight lines "