prj_name: 'LAR_3_apx'
trj: "/media/topo/Data/Data/ALS/libor/in/trj/SBET_02_GNSS_INS_APX_fromDN.out"

p2p_folder: "/media/topo/Data/Data/ALS/libor/in/p2p/aclens/3fl_apx/"

t_span: [396500.0, 398000.0]

mount:
  leverArm: [[-0.042], [0.183], [-0.021]] #m
  R_s2b: [[0, -1, 0], [0, 0, -1], [1, 0, 0]]
  initBor: [[0.0], [0.0], [0.0]] #degrees rpy

tp_latlon: [46.5, 6.5] #decimal degrees

sampling:
  strategy: 'max'
  value: 5000

refBor: [[-0.212], [0.100], [0.191]] # orig. calib.

sigmas: # meters and degrees
  xy: 0.01 
  z:  0.03
  rp: 0.025
  y:  0.080
  p2p: 0.1


riprocess:
  rpy: [-0.158,0.087,0.293]
  std: [0.002,0.002,0.008]
  plane_num: 1630
  p_sig_prio: 0.288
  p_sig_post: 0.133

dn:
  rpy: [-0.215,0.070,0.209]
  std: [0.013,0.003,0.004]

output:
  folder: '/media/topo/Data/Data/ALS/libor/out/nominal/'
  fig_svg: true

info: "Aclens - 3 flight lines (cross pattern) - APX 15"

