# Libor configuration file
prj_name: 'LAR_2'
trj: "/media/topo/Data/Data/ALS/libor/in/trj/SBET_MILF18_200HZ_aclens.out"

p2p_folder: "/media/topo/Data/Data/ALS/libor/in/p2p/aclens/2fl_nobor/"

t_span: [396500.0, 398000.0]

mount:
  leverArm: [[-0.042], [0.183], [-0.021]] #m
  R_s2b: [[0, -1, 0], [0, 0, -1], [1, 0, 0]]
  initBor: [[0.0] , [0.0], [0.0]] #degrees rpy

tp_latlon: [46.5, 6.5] #decimal degrees

sampling:
  strategy: 'max'
  value: 2500

refBor: [[-0.212], [0.100], [0.191]] # orig. calib.

sigmas: # meters and degrees
  xy: 0.01 
  z:  0.01
  rp: 0.0025
  y:  0.005
  p2p: 0.05

riprocess:
  rpy: [-0.204,0.080,0.115]
  std: [0.002,0.007,0.030]
  plane_num: 1259
  p_sig_prio: 0.28
  p_sig_post: 0.08

dn:
  rpy: [-0.211,0.093,0.197]
  std: [0.0008,0.0006,0.0007]

output:
  folder: '/media/topo/Data/Data/ALS/libor/out/nominal/'
  fig_svg: true

info: "Aclens - 2 flight lines (cross)"