# Libor configuration file
prj_name: 'LEG_2'
trj: "/media/topo/Data/Data/ALS/libor/in/trj/SBET_sion_legacy_400HZ.OUT"
p2p_folder: "/media/topo/Data/Data/ALS/libor/in/p2p/legacy_sion/2fl/"

t_span: [216300.0, 216947.9] #must englobe p2p timestamps

mount:  
  leverArm: [[0.178], [0.056], [0.071]] #m
  R_s2b: [[0, -1, 0], [0, 0, 1], [-1, 0, 0]]
  initBor: [[0.0] , [0.0], [0.0]] #degrees rpy

tp_latlon: [46.24, 7.37] #decimal degrees

sampling:
  strategy: 'max'
  value: 500
refBor: [[0.139], [-0.060], [-0.057]]  # plane to plane libor

sigmas:  # meters and degrees
  xy: 0.015
  z:  0.015
  rp: 0.005
  y:  0.01
  p2p: 0.1

riprocess:
  rpy: [0.136, -0.071, 0.007]
  std: [0.0066,0.0035,0.0287]
  plane_num: 16
  p_sig_prio: 0.17
  p_sig_post: 0.02

dn:
  rpy: [0.141,-0.057,-0.030]
  std: [0.0022,0.0006,0.0007]

output:
  folder: '/media/topo/Data/Data/ALS/libor/out/nominal/'
  fig_svg: true

info: "Sion Legacy - 2 flight lines (cross, different height -> Relatively high observability depsite using only 2 fl) "