# Libor configuration file
prj_name: 'MLS Helimap iteration1'
trj: "/media/topo/Data/Data/ALS/libor/in/trj/MLS_helimap.out"
p2p_folder: "/media/topo/Data/Data/ALS/libor/in/p2p/mls_helimap/it1/"

t_span: [305200, 306590] #must englobe p2p timestamps

mount:
  leverArm: [[0.0], [0.0], [0.0]] #m
  R_s2b: [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
  initBor: [[0], [0], [0]] #degrees rpy

tp_latlon: [46.24, 7.37] #decimal degrees
sampling:
  strategy: 'max'
  value: 5000

refBor: [[0.0], [0.0], [0.0]] # plane to plane libor

sigmas:  # meters and degrees
  xy: 0.02
  z:  0.03
  rp: 0.025
  y:  0.005
  p2p: 0.10



output:
  folder: '/media/topo/LaCie/2026_RD/boresight/libor/it1/'
  fig_svg: true

info: "MLS helimap with second iteration limatch"