# Libor configuration file
prj_name: 'Sion'
trj: "/media/topo/Data/Data/ALS/Sion/01_trj/SBET_CALIB400HZ.OUT"
p2p_folder: "/media/topo/Data/Data/ALS/Sion/03_p2p/cor_outputs/libor_secAttempt/"

t_span: [315000.0, 318250.0] #must englobe p2p timestamps

mount:
  leverArm: [[0.0], [-0.231], [0.071]] #m
  R_s2b: [[0, -1, 0], [0, 0, 1], [-1, 0, 0]]
  initBor: [[0.0] , [0.0], [0.0]] #degrees rpy

tp_latlon: [46.2, 7.35] #decimal degrees

n: 1500 #num cor used in adj.

refBor: [[-0.002], [-0.433], [0.186]]#degrees

sigmas:  # meters and degrees
  xy: 0.02
  z:  0.03
  rp: 0.01
  y:  0.02
  p2p: 0.1

logFolder: '/media/topo/Data/Data/ALS/libor/'